global ERROR_CODE_TYPE;
ERROR_CODE_TYPE.DEADLINE_MISSED = 0;
ERROR_CODE_TYPE.APPLICATION_ERROR = 1;
ERROR_CODE_TYPE.NUMERIC_ERROR = 2;
ERROR_CODE_TYPE.ILLEGAL_REQUEST = 3;
ERROR_CODE_TYPE.STACK_OVERFLOW = 4;
ERROR_CODE_TYPE.MEMORY_VIOLATION = 5;
ERROR_CODE_TYPE.HARDWARE_FAULT = 6;
ERROR_CODE_TYPE.POWER_FAIL = 7;