function [RETURN_CODE] = REPORT_APPLICATION_MESSAGE(MESSAGE_ADDR,LENGTH)

global RETURN_CODE_TYPE;

if LENGTH < 0 || LENGTH >128
    RETURN_CODE = RETURN_CODE_TYPE.INVALID_PARAM
    return;
end

HM_FUNCTION(MESSAGE_ADDR,LENGTH);

RETURN_CODE = RETURN_CODE_TYPE.NO_ERROR
return;

end
